### ISSUE TITLE
Add: Responsive Carrito + Fix: footer y headers de todo proyecto

### ISSUE THREAD

**Issue by MarianoXinos1** [DH-Comision-07/grupo_3_DH-Records#192]
- [x] Fix: footers general.
- [x] Fix: headers general.
- [x] Responsive Carrito mobile
- [x] Responsive Carrito ipad
